version: '3.9'

services:
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ~/Documents/data/activemq/data:/data/activemq
      - ~/Documents/data/activemq/log:/var/log/activemq